main: # 触发分支
  push: # 触发事件
    - docker:
        image: node:22 # 流水线执行环境，可以指定任意docker镜像
      stages:
        - name: install
          script: npm install
        - name: test
          script: npm test

# 云原生开发环境配置
workspace:
  # 使用自定义 Dockerfile
  dockerfile: "./Dockerfile"
  
  # 端口映射
  ports:
    - "3000:3000"  # Nuxt 默认端口
    - "5173:5173"  # Vite 默认端口
    - "8080:8080"  # 备用端口
  
  # 环境变量
  env:
    NODE_ENV: "development"
    PNPM_HOME: "/root/.local/share/pnpm"
  
  # 启动命令
  startup_commands:
    - "chmod +x /workspace/scripts/init-dev.sh"
    - "/workspace/scripts/init-dev.sh"
  
  # 开发工具配置
  tools:
    editor:
      type: "vscode"
      extensions:
        - "ms-vscode.vscode-typescript-next"
        - "bradlc.vscode-tailwindcss"
        - "esbenp.prettier-vscode"
        - "ms-vscode.vscode-eslint"
        - "Vue.volar"
        - "ms-vscode.vscode-json"